### ISSUE TITLE
Gitlab?

### ISSUE THREAD

**Issue by PythonDevOp** [GitbookIO/nuts#139]
The documentation states that this can work with other backends. Does this work with Gitlab currently, or are there currently any pull requests to get it working with Gitlab? I am guessing the answer is NO on both fronts, but I wanted to confirm

**Comment by AaronO** [comment]
@PythonDevOp It's designed to support other backends but only the `github` backend is implemented since that's the only one we use. So for now "no" on both fronts. 

Take a look at the backend code https://github.com/GitbookIO/nuts/tree/master/lib/backends, it's fairly straight forward and assuming GitLab's APIs aren't lacking it should be quite easy to implement.

It's highly unlikely we'll implement a GitLab backend since we don't use GitLab but a high-quality PR could be merged.
