### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by hermanocabral** [GitbookIO/nuts#147]
Just looking to use this but a quick look at the issues/pull requests makes me wonder if this project is dead... Is it?

**Comment by cyberious** [comment]
I also would like to know if this is dead?

**Comment by SamyPesse** [comment]
This project is not dead, but we don't have an active maintainer in the team for it (we are a team of 4 developers).

Nuts is being used in production by GitBook, and running without issues since two years.

If someone is interested by helping maintaining this repository, I'll be happy to discuss it 🍻

**Comment by DxCx** [comment]
hi @SamyPesse i have some patches i would like to contribute (after making sure everything is working on our production):
1. Updating docker base image to node:8-alpine
2. Add new endpoint to be used with `electron-updater` which generates latest.yml & latest-mac.yml from github assets. (This enables NSIS updates too)

is this something you might want in?
i'm trying to keep changes isolated at the moment so i can open PRs later, but since project is not that active i'm not sure =)
