### ISSUE TITLE
Forcing HTTPS responses? Attempts to fix ATS errors

### ISSUE THREAD

**Issue by raphaelschaad** [GitbookIO/nuts#169]
Is forcing HTTPS responses a good idea? https://medium.com/@connorlurring/fixing-nuts-auto-updates-for-our-electron-app-64beeed8b14 /by @connorlurring

The author attempts to fix Apple Transport Security (ATS) errors when the an Electron client requests the update through HTTPS but then the nuts deployment setup (Heroku in this case) returns an HTTP URL. /cc @SamyPesse @AaronO

**Comment by ogtfaber** [comment]
You can solve this by setting `TRUST_PROXY` to `true` in Heroku

See https://github.com/GitbookIO/nuts/issues/163#issuecomment-468916045

**Comment by connorlurring** [comment]
Hi @raphaelschaad thanks for taking the time to critically evaluate my article!

While forcing HTTPS isn't the _optimal_ solution, it has worked for my use case since that article was written, with no unforeseen issues.

That said, thanks @ogtfaber for bringing #163 to my attention. `TRUST_PROXY` sounds like a valid solution, I plan to amend the article shortly to recommend it. I wasn't aware that there was a commonplace solution for trusting the proxy in a situation like this, and the original solution was based on the Heroku documentation not having any reference to this config var.

It seems that `TRUST_PROXY` is a commonly used configuration for a variety of products, and should be more generally suitable as advice, leaving the original functionality of the library unchanged.

**Comment by raphaelschaad** [comment]
Thanks @ogtfaber for the solution, I have since adopted it. And thanks @connorlurring for updating your post for everyone else, given you're the top result I found googling the problem. You can point to [the relevant bits of Nuts' docs](https://github.com/GitbookIO/nuts/commit/8ff7ba3692008c505e889af46ea05b94b126f79a). Closing this issue.
